/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Manager */
        get: operations["current_manager_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime */
        get: operations["runtime_api_telegram_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_technicians__identifier__telegram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue */
        post: operations["issue_api_technicians__identifier__telegram_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/invitations/{invitation_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_api_technicians__identifier__telegram_invitations__invitation_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/invitations/{invitation_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_technicians__identifier__telegram_invitations__invitation_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/invitations/{invitation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_technicians__identifier__telegram_invitations__invitation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect */
        post: operations["disconnect_api_technicians__identifier__telegram_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{identifier}/telegram/test-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Message */
        post: operations["test_message_api_technicians__identifier__telegram_test_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Technicians */
        get: operations["list_technicians_api_technicians_get"];
        put?: never;
        /** Create Technician */
        post: operations["create_technician_api_technicians_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{technician_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Technician */
        get: operations["get_technician_api_technicians__technician_id__get"];
        put?: never;
        post?: never;
        /** Delete Technician */
        delete: operations["delete_technician_api_technicians__technician_id__delete"];
        options?: never;
        head?: never;
        /** Update Technician */
        patch: operations["update_technician_api_technicians__technician_id__patch"];
        trace?: never;
    };
    "/api/technicians/{technician_id}/calendar-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignment History */
        get: operations["assignment_history_api_technicians__technician_id__calendar_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{technician_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Calendar */
        put: operations["set_calendar_api_technicians__technician_id__calendar_put"];
        post?: never;
        /** Remove Calendar Assignment */
        delete: operations["remove_calendar_assignment_api_technicians__technician_id__calendar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calendars */
        get: operations["list_calendars_api_calendars_get"];
        put?: never;
        /** Create Calendar */
        post: operations["create_calendar_api_calendars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendars/{calendar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Calendar */
        delete: operations["delete_calendar_api_calendars__calendar_id__delete"];
        options?: never;
        head?: never;
        /** Rename Calendar */
        patch: operations["rename_calendar_api_calendars__calendar_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignedTechnician */
        AssignedTechnician: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** AssignmentInput */
        AssignmentInput: {
            /**
             * Calendar Id
             * Format: uuid
             */
            calendar_id: string;
        };
        /** AssignmentRead */
        AssignmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /** Calendar Id */
            calendar_id: string | null;
            /** Calendar Name */
            calendar_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalendarCreate */
        CalendarCreate: {
            /** Name */
            name: string;
        };
        /** CalendarDelete */
        CalendarDelete: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "DELETE";
            /**
             * Detach Assigned
             * @default false
             */
            detach_assigned: boolean;
        };
        /** CalendarRead */
        CalendarRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            assigned_technician?: components["schemas"]["AssignedTechnician"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalendarSummary */
        CalendarSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ConnectionRead */
        ConnectionRead: {
            /** State */
            state: string;
            /** Approved */
            approved: boolean;
            /** Generation */
            generation: number;
            /** Availability */
            availability: string;
            /** Telegram Id */
            telegram_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Username */
            username?: string | null;
            /**
             * Replacement Pending
             * @default false
             */
            replacement_pending: boolean;
            invitation?: components["schemas"]["InvitationRead"] | null;
        };
        /** DeliveryRead */
        DeliveryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Destination */
            destination: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
            /** Error Code */
            error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Disconnect */
        Disconnect: {
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "PRIVATE_TELEGRAM" | "WORK_GROUP";
            /** Expected Generation */
            expected_generation: number;
            /**
             * Confirmation
             * @constant
             */
            confirmation: "DISCONNECT";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** IntegrationSummary */
        IntegrationSummary: {
            /**
             * Telegram Private
             * @default NOT_CONNECTED
             * @enum {string}
             */
            telegram_private: "NOT_CONNECTED" | "PENDING" | "CONNECTED" | "ERROR";
            /**
             * Telegram Group
             * @default NOT_CONNECTED
             * @enum {string}
             */
            telegram_group: "NOT_CONNECTED" | "PENDING" | "CONNECTED" | "ERROR";
            /**
             * Gps Provider
             * @default NONE
             * @enum {string}
             */
            gps_provider: "NONE" | "MOTOWATCHDOG_SHARE";
            /**
             * Gps Status
             * @default NOT_CONNECTED
             * @enum {string}
             */
            gps_status: "NOT_CONNECTED" | "PENDING" | "CONNECTED" | "ERROR";
        };
        /** InvitationRead */
        InvitationRead: {
            /** Automatic */
            automatic: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "PRIVATE_TELEGRAM" | "WORK_GROUP";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** State */
            state: string;
            /** Candidate User Id */
            candidate_user_id?: string | null;
            /** Candidate Display Name */
            candidate_display_name?: string | null;
            /** Candidate Username */
            candidate_username?: string | null;
            /** Candidate Chat Id */
            candidate_chat_id?: string | null;
            /** Candidate Chat Title */
            candidate_chat_title?: string | null;
            /** Initiator Admin */
            initiator_admin?: boolean | null;
            /** Bot Admin */
            bot_admin?: boolean | null;
            /** Technician Member */
            technician_member?: boolean | null;
            /** Verified At */
            verified_at?: string | null;
            /** Setup Error */
            setup_error?: string | null;
        };
        /** IssueInvitation */
        IssueInvitation: {
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "PRIVATE_TELEGRAM" | "WORK_GROUP";
            /**
             * Replace
             * @default false
             */
            replace: boolean;
            /** Expected Generation */
            expected_generation: number;
            /**
             * Confirmation
             * @enum {string}
             */
            confirmation: "CONNECT" | "REPLACE";
        };
        /** IssuedInvitation */
        IssuedInvitation: {
            invitation: components["schemas"]["InvitationRead"];
            /** Link */
            link: string;
            /** Fallback Command */
            fallback_command?: string | null;
        };
        /** Login */
        Login: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ManagerRead */
        ManagerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ReviewInvitation */
        ReviewInvitation: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REJECT";
        };
        /** RuntimeRead */
        RuntimeRead: {
            /** Mode */
            mode: string;
            /** State */
            state: string;
            /** Bot Username */
            bot_username: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Error Code */
            error_code?: string | null;
        };
        /** TechnicianCreate */
        TechnicianCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Calendar Id */
            calendar_id?: string | null;
        };
        /** TechnicianDelete */
        TechnicianDelete: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "DELETE";
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
        };
        /** TechnicianDetail */
        TechnicianDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            calendar: components["schemas"]["CalendarSummary"] | null;
            integrations: components["schemas"]["IntegrationSummary"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Driver License Id */
            driver_license_id: string | null;
            /** Ssn Last4 */
            ssn_last4: string | null;
        };
        /** TechnicianSummary */
        TechnicianSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            calendar: components["schemas"]["CalendarSummary"] | null;
            integrations: components["schemas"]["IntegrationSummary"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TechnicianUpdate */
        TechnicianUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Status */
            status?: ("ACTIVE" | "INACTIVE") | null;
            /** Driver License Id */
            driver_license_id?: string | null;
            /** Ssn Last4 */
            ssn_last4?: string | null;
        };
        /** TelegramState */
        TelegramState: {
            private: components["schemas"]["ConnectionRead"];
            group: components["schemas"]["ConnectionRead"];
            runtime: components["schemas"]["RuntimeRead"];
            /** Deliveries */
            deliveries: components["schemas"]["DeliveryRead"][];
        };
        /** TestMessage */
        TestMessage: {
            /**
             * Destination
             * @enum {string}
             */
            destination: "PRIVATE_TELEGRAM" | "WORK_GROUP";
            /** Expected Generation */
            expected_generation: number;
            /**
             * Confirmation
             * @constant
             */
            confirmation: "SEND TEST";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_in_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_manager_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerRead"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runtime_api_telegram_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeRead"];
                };
            };
        };
    };
    state_api_technicians__identifier__telegram_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_technicians__identifier__telegram_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueInvitation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_technicians__identifier__telegram_invitations__invitation_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_technicians__identifier__telegram_invitations__invitation_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInvitation"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_technicians__identifier__telegram_invitations__invitation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_technicians__identifier__telegram_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Disconnect"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_message_api_technicians__identifier__telegram_test_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_technicians_api_technicians_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_technician_api_technicians_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicianCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technician_api_technicians__technician_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_technician_api_technicians__technician_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicianDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_technician_api_technicians__technician_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicianUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignment_history_api_technicians__technician_id__calendar_assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_calendar_api_technicians__technician_id__calendar_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_calendar_assignment_api_technicians__technician_id__calendar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendars_api_calendars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"][];
                };
            };
        };
    };
    create_calendar_api_calendars_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_calendar_api_calendars__calendar_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_calendar_api_calendars__calendar_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
