"""add durable schedule delivery"""

import sqlalchemy as sa
from alembic import op

revision = "d4e509170001"
down_revision = "c3e410a20917"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_worker_states",
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("pk_schedule_worker_states")),
    )
    op.create_table(
        "schedule_auto_decisions",
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("source_date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_schedule_auto_decisions_technician_id_technicians"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "technician_id", "target_date", name=op.f("pk_schedule_auto_decisions")
        ),
    )
    op.create_table(
        "schedule_delivery_settings",
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_schedule_delivery_settings_technician_id_technicians"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("technician_id", name=op.f("pk_schedule_delivery_settings")),
    )
    op.create_table(
        "schedule_dispatches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_id", sa.Uuid(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("destination", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column("encrypted_payload", sa.Text(), nullable=True),
        sa.Column("payload_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claim_owner", sa.Uuid(), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ack_status", sa.String(length=16), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ack_token_hash", sa.String(length=64), nullable=True),
        sa.Column("ack_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("private_generation", sa.Integer(), nullable=False),
        sa.Column("group_generation", sa.Integer(), nullable=False),
        sa.Column("resend_of_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(ack_status = 'ACKNOWLEDGED') = (acknowledged_at IS NOT NULL)",
            name=op.f("ck_schedule_dispatches_ack_time"),
        ),
        sa.CheckConstraint(
            "(status = 'PROCESSING') = (claim_owner IS NOT NULL AND claim_expires_at IS NOT NULL)",
            name=op.f("ck_schedule_dispatches_claim"),
        ),
        sa.CheckConstraint(
            "(status = 'SENT' AND ack_status IN ('PENDING','ACKNOWLEDGED')) "
            "OR (status <> 'SENT' AND ack_status = 'NOT_SENT')",
            name=op.f("ck_schedule_dispatches_ack_delivery"),
        ),
        sa.CheckConstraint(
            "(status = 'SENT') = (sent_at IS NOT NULL AND message_id IS NOT NULL)",
            name=op.f("ck_schedule_dispatches_sent"),
        ),
        sa.CheckConstraint(
            "ack_status IN ('NOT_SENT','PENDING','ACKNOWLEDGED')",
            name=op.f("ck_schedule_dispatches_ack_status"),
        ),
        sa.CheckConstraint(
            "destination IN ('WORK_GROUP','PRIVATE')",
            name=op.f("ck_schedule_dispatches_destination"),
        ),
        sa.CheckConstraint(
            "fingerprint ~ '^[0-9a-f]{64}$'", name=op.f("ck_schedule_dispatches_fingerprint")
        ),
        sa.CheckConstraint(
            "status <> 'SENT' OR encrypted_payload IS NULL",
            name=op.f("ck_schedule_dispatches_sent_payload_purged"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','PROCESSING','SENT','FAILED','AMBIGUOUS','CANCELLED')",
            name=op.f("ck_schedule_dispatches_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('PENDING','PROCESSING') OR encrypted_payload IS NOT NULL",
            name=op.f("ck_schedule_dispatches_active_payload"),
        ),
        sa.CheckConstraint(
            "trigger IN ('MANUAL','AUTOMATIC','MANUAL_RESEND')",
            name=op.f("ck_schedule_dispatches_trigger"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND job_count >= 0", name=op.f("ck_schedule_dispatches_counts")
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
            name=op.f("fk_schedule_dispatches_calendar_id_calendars"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["managers.id"],
            name=op.f("fk_schedule_dispatches_created_by_managers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resend_of_id"],
            ["schedule_dispatches.id"],
            name=op.f("fk_schedule_dispatches_resend_of_id_schedule_dispatches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_schedule_dispatches_technician_id_technicians"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_dispatches")),
        sa.UniqueConstraint("ack_token_hash", name=op.f("uq_schedule_dispatches_ack_token_hash")),
        sa.CheckConstraint(
            "(claim_owner IS NULL) = (claim_expires_at IS NULL)",
            name=op.f("ck_schedule_dispatches_claim_pair"),
        ),
        sa.CheckConstraint(
            "(sent_at IS NULL) = (message_id IS NULL)",
            name=op.f("ck_schedule_dispatches_sent_pair"),
        ),
        sa.CheckConstraint(
            "(ack_token_hash IS NULL) = (ack_expires_at IS NULL)",
            name=op.f("ck_schedule_dispatches_ack_pair"),
        ),
        sa.CheckConstraint(
            "ack_status = 'NOT_SENT' OR ack_token_hash IS NOT NULL",
            name=op.f("ck_schedule_dispatches_ack_capability"),
        ),
        sa.CheckConstraint(
            "(status IN ('PENDING','PROCESSING')) = (finished_at IS NULL)",
            name=op.f("ck_schedule_dispatches_finished"),
        ),
        sa.CheckConstraint(
            "(trigger = 'MANUAL_RESEND') = (resend_of_id IS NOT NULL)",
            name=op.f("ck_schedule_dispatches_resend_parent"),
        ),
        sa.CheckConstraint(
            "encrypted_payload IS NULL OR encrypted_payload LIKE 'v1:%'",
            name=op.f("ck_schedule_dispatches_cipher_version"),
        ),
        sa.UniqueConstraint("resend_of_id", name=op.f("uq_schedule_dispatches_resend_of_id")),
    )
    op.create_index(
        "ix_schedule_claim", "schedule_dispatches", ["status", "available_at"], unique=False
    )
    op.create_index(
        "ix_schedule_history", "schedule_dispatches", ["technician_id", "created_at"], unique=False
    )
    op.create_index(
        "uq_schedule_active_day",
        "schedule_dispatches",
        ["technician_id", "target_date"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','PROCESSING')"),
    )
    op.create_index(
        "uq_schedule_auto_day",
        "schedule_dispatches",
        ["technician_id", "target_date"],
        unique=True,
        postgresql_where=sa.text("trigger = 'AUTOMATIC'"),
    )
    op.execute("""
        CREATE FUNCTION guard_schedule_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF ROW(NEW.technician_id, NEW.target_date, NEW.fingerprint, NEW.source_version,
                 NEW.job_count, NEW.trigger, NEW.bot_id, NEW.telegram_user_id,
                 NEW.private_generation, NEW.group_generation, NEW.resend_of_id)
             IS DISTINCT FROM
             ROW(OLD.technician_id, OLD.target_date, OLD.fingerprint, OLD.source_version,
                 OLD.job_count, OLD.trigger, OLD.bot_id, OLD.telegram_user_id,
                 OLD.private_generation, OLD.group_generation, OLD.resend_of_id)
             OR (NEW.encrypted_payload IS NOT NULL
                 AND NEW.encrypted_payload IS DISTINCT FROM OLD.encrypted_payload)
             OR (OLD.status IN ('SENT','AMBIGUOUS','FAILED','CANCELLED')
                 AND NEW.status <> OLD.status)
          THEN RAISE EXCEPTION 'SCHEDULE_IMMUTABLE' USING ERRCODE = '23514'; END IF;
          RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER schedule_snapshot_immutable BEFORE UPDATE ON schedule_dispatches
          FOR EACH ROW EXECUTE FUNCTION guard_schedule_snapshot();
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_schedule_auto_day",
        table_name="schedule_dispatches",
        postgresql_where=sa.text("trigger = 'AUTOMATIC'"),
    )
    op.drop_index(
        "uq_schedule_active_day",
        table_name="schedule_dispatches",
        postgresql_where=sa.text("status IN ('PENDING','PROCESSING')"),
    )
    op.drop_index("ix_schedule_history", table_name="schedule_dispatches")
    op.drop_index("ix_schedule_claim", table_name="schedule_dispatches")
    op.drop_table("schedule_dispatches")
    op.execute("DROP FUNCTION IF EXISTS guard_schedule_snapshot()")
    op.drop_table("schedule_delivery_settings")
    op.drop_table("schedule_auto_decisions")
    op.drop_table("schedule_worker_states")
    # ### end Alembic commands ###
