"""add technician work reports"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e5f509180001"
down_revision = "d4e509170002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_key", sa.String(length=64), nullable=False),
        sa.Column("current_revision_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_revision_number > 0", name=op.f("ck_work_reports_current_revision")
        ),
        sa.CheckConstraint("length(occurrence_key) = 64", name=op.f("ck_work_reports_occurrence")),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
            name=op.f("fk_work_reports_calendar_id_calendars"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_work_reports_technician_id_technicians"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_reports")),
        sa.UniqueConstraint(
            "technician_id", "calendar_id", "occurrence_key", name="uq_work_report_occurrence"
        ),
    )
    op.create_index(
        op.f("ix_work_reports_technician_id"), "work_reports", ["technician_id"], unique=False
    )
    op.create_table(
        "technician_form_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=20), server_default="WORK_REPORT", nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("binding_generation", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("selected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'SUBMITTED') = (report_id IS NOT NULL "
            "AND submitted_at IS NOT NULL AND payload_hash IS NOT NULL)",
            name=op.f("ck_technician_form_sessions_submission"),
        ),
        sa.CheckConstraint(
            "purpose = 'WORK_REPORT'", name=op.f("ck_technician_form_sessions_purpose")
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','SUBMITTED','EXPIRED','REVOKED')",
            name=op.f("ck_technician_form_sessions_status"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_technician_form_sessions_expiry")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["work_reports.id"],
            name=op.f("fk_technician_form_sessions_report_id_work_reports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_technician_form_sessions_technician_id_technicians"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_form_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_technician_form_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_technician_form_sessions_technician_id"),
        "technician_form_sessions",
        ["technician_id"],
        unique=False,
    )
    op.create_table(
        "work_report_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("technician_name", sa.String(length=250), nullable=False),
        sa.Column("operational_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.String(length=16), nullable=False),
        sa.Column("end_time", sa.String(length=16), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("location", sa.String(length=1000), nullable=False),
        sa.Column("provider_event_id", sa.String(length=1024), nullable=False),
        sa.Column("recurring_event_id", sa.String(length=1024), nullable=True),
        sa.Column("original_start_time", sa.String(length=64), nullable=True),
        sa.Column("amount_closed", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("closed_by", sa.String(length=20), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("yearly_maintenance_plan_provided", sa.Boolean(), nullable=False),
        sa.Column("google_reviews", sa.Integer(), nullable=False),
        sa.Column("groupon_reviews", sa.Integer(), nullable=False),
        sa.Column("facebook_reviews", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "closed_by IN ('MYSELF','CALL_CENTER')", name=op.f("ck_work_report_revisions_closer")
        ),
        sa.CheckConstraint(
            "payment_method IN ('CASH','ZELLE','CHECK','CREDIT_CARD',"
            "'VENMO','SUPER','ESTIMATE','CANCEL')",
            name=op.f("ck_work_report_revisions_payment"),
        ),
        sa.CheckConstraint(
            "payment_method NOT IN ('ESTIMATE','CANCEL') OR amount_closed = 0",
            name=op.f("ck_work_report_revisions_zero_amount"),
        ),
        sa.CheckConstraint(
            "amount_closed >= 0 AND amount_closed <= 9999999999.99",
            name=op.f("ck_work_report_revisions_money"),
        ),
        sa.CheckConstraint(
            "google_reviews BETWEEN 0 AND 100 AND groupon_reviews BETWEEN 0 AND 100 "
            "AND facebook_reviews BETWEEN 0 AND 100",
            name=op.f("ck_work_report_revisions_reviews"),
        ),
        sa.CheckConstraint(
            "length(comments) <= 4000", name=op.f("ck_work_report_revisions_comments")
        ),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_work_report_revisions_positive_revision")
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_work_report_revisions_sequence")),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["work_reports.id"],
            name=op.f("fk_work_report_revisions_report_id_work_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_report_revisions")),
        sa.UniqueConstraint("report_id", "revision_number", name="uq_work_report_revision"),
    )
    op.create_foreign_key(
        "fk_work_report_current_revision",
        "work_reports",
        "work_report_revisions",
        ["id", "current_revision_number"],
        ["report_id", "revision_number"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.execute("""
      CREATE FUNCTION guard_work_report_history() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        RAISE EXCEPTION 'WORK_REPORT_HISTORY_IMMUTABLE' USING ERRCODE = '23514';
      END $$;
    """)
    op.execute(
        "CREATE TRIGGER work_report_revision_immutable BEFORE UPDATE OR DELETE "
        "ON work_report_revisions FOR EACH ROW EXECUTE FUNCTION guard_work_report_history()"
    )
    op.execute(
        "CREATE TRIGGER work_report_identity_immutable BEFORE UPDATE OR DELETE "
        "ON work_reports FOR EACH ROW EXECUTE FUNCTION guard_work_report_history()"
    )
    op.execute("""
      CREATE FUNCTION guard_submitted_form() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF OLD.status = 'SUBMITTED' AND NEW IS DISTINCT FROM OLD
        THEN RAISE EXCEPTION 'FORM_ALREADY_SUBMITTED' USING ERRCODE = '23514'; END IF;
        RETURN NEW;
      END $$;
    """)
    op.execute(
        "CREATE TRIGGER submitted_form_immutable BEFORE UPDATE ON technician_form_sessions "
        "FOR EACH ROW EXECUTE FUNCTION guard_submitted_form()"
    )


def downgrade():
    op.execute("""DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM work_reports) OR EXISTS (SELECT 1 FROM work_report_revisions)
      THEN RAISE EXCEPTION 'WORK_REPORT_HISTORY_ROLLBACK_REFUSED'; END IF;
    END $$""")
    op.drop_constraint("fk_work_report_current_revision", "work_reports", type_="foreignkey")
    op.execute("DROP FUNCTION guard_submitted_form() CASCADE")
    op.execute("DROP FUNCTION guard_work_report_history() CASCADE")
    op.drop_table("work_report_revisions")
    op.drop_index(
        op.f("ix_technician_form_sessions_technician_id"), table_name="technician_form_sessions"
    )
    op.drop_table("technician_form_sessions")
    op.drop_index(op.f("ix_work_reports_technician_id"), table_name="work_reports")
    op.drop_table("work_reports")
    # ### end Alembic commands ###
