"""add technician expenses"""

import sqlalchemy as sa
from alembic import op

revision = "f6e609180001"
down_revision = "e5f509180003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "technician_expenses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column("current_revision_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_revision_number > 0", name=op.f("ck_technician_expenses_current_revision")
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.id"],
            name=op.f("fk_technician_expenses_technician_id_technicians"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technician_expenses")),
    )
    op.create_index(
        op.f("ix_technician_expenses_technician_id"),
        "technician_expenses",
        ["technician_id"],
        unique=False,
    )
    op.create_table(
        "expense_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("expense_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("technician_name", sa.String(length=250), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("accounting_timezone", sa.String(length=64), nullable=False),
        sa.Column("expense_type", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expense_date BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'",
            name=op.f("ck_expense_revisions_date"),
        ),
        sa.CheckConstraint(
            "length(trim(expense_type)) BETWEEN 1 AND 100 AND expense_type !~ '[<>[:cntrl:]]'",
            name=op.f("ck_expense_revisions_type"),
        ),
        sa.CheckConstraint(
            "amount >= 0 AND amount <= 9999999999.99", name=op.f("ck_expense_revisions_money")
        ),
        sa.CheckConstraint("length(note) <= 4000", name=op.f("ck_expense_revisions_note")),
        sa.CheckConstraint("length(technician_name) > 0", name=op.f("ck_expense_revisions_name")),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_expense_revisions_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["technician_expenses.id"],
            name=op.f("fk_expense_revisions_expense_id_technician_expenses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_revisions")),
        sa.UniqueConstraint("expense_id", "revision_number", name="uq_expense_revision"),
    )
    op.create_index(
        op.f("ix_expense_revisions_expense_date"),
        "expense_revisions",
        ["expense_date"],
        unique=False,
    )
    op.add_column("technician_form_sessions", sa.Column("expense_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_technician_form_sessions_expense_id_technician_expenses"),
        "technician_form_sessions",
        "technician_expenses",
        ["expense_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "technicians", sa.Column("accounting_timezone", sa.String(length=64), nullable=True)
    )
    op.create_foreign_key(
        "fk_expense_current_revision",
        "technician_expenses",
        "expense_revisions",
        ["id", "current_revision_number"],
        ["expense_id", "revision_number"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.drop_constraint(op.f("ck_technician_form_sessions_purpose"), "technician_form_sessions")
    op.create_check_constraint(
        op.f("ck_technician_form_sessions_purpose"),
        "technician_form_sessions",
        "purpose IN ('WORK_REPORT','EXPENSE')",
    )
    op.drop_constraint(op.f("ck_technician_form_sessions_submission"), "technician_form_sessions")
    op.create_check_constraint(
        op.f("ck_technician_form_sessions_submission"),
        "technician_form_sessions",
        (
            "(status = 'SUBMITTED' AND ((purpose = 'WORK_REPORT' AND report_id IS "
            "NOT NULL AND expense_id IS NULL) OR (purpose = 'EXPENSE' AND "
            "expense_id IS NOT NULL AND report_id IS NULL)) AND submitted_at IS "
            "NOT NULL AND payload_hash IS NOT NULL) OR (status <> 'SUBMITTED' AND "
            "report_id IS NULL AND expense_id IS NULL AND submitted_at IS NULL AND "
            "payload_hash IS NULL)"
        ),
    )
    op.execute("""CREATE FUNCTION guard_expense_history() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'EXPENSE_HISTORY_IMMUTABLE' USING ERRCODE='23514'; END $$""")
    for table in ("technician_expenses", "expense_revisions"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION guard_expense_history()"
        )
    op.execute("""CREATE FUNCTION guard_expense_sequence() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE target uuid; pointer integer; total bigint; first_number integer;
last_number integer;
      BEGIN
        IF TG_TABLE_NAME = 'technician_expenses' THEN target := NEW.id; ELSE target :=
NEW.expense_id; END IF;
        SELECT current_revision_number INTO pointer FROM technician_expenses WHERE
id=target;
        SELECT count(*),min(revision_number),max(revision_number) INTO
total,first_number,last_number FROM expense_revisions WHERE expense_id=target;
        IF pointer IS NULL OR total <> pointer OR first_number <> 1 OR last_number <>
pointer
        THEN RAISE EXCEPTION 'EXPENSE_REVISION_SEQUENCE_INVALID' USING ERRCODE='23514';
END IF;
        RETURN NULL;
      END $$""")
    for table in ("technician_expenses", "expense_revisions"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER {table}_sequence AFTER INSERT ON {table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION guard_expense_sequence()"
        )
    op.execute("""CREATE FUNCTION guard_accounting_timezone() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF NEW.accounting_timezone IS NOT NULL AND NOT EXISTS (SELECT 1 FROM
pg_timezone_names WHERE name=NEW.accounting_timezone)
        THEN RAISE EXCEPTION 'INVALID_ACCOUNTING_TIMEZONE' USING ERRCODE='23514'; END IF;
        IF TG_TABLE_NAME = 'expense_revisions' THEN
          IF NEW.expense_date <> (NEW.submitted_at AT TIME ZONE
NEW.accounting_timezone)::date
          THEN RAISE EXCEPTION 'EXPENSE_DATE_MISMATCH' USING ERRCODE='23514'; END IF;
        END IF;
        RETURN NEW;
      END $$""")
    op.execute(
        "CREATE TRIGGER technician_accounting_timezone BEFORE INSERT OR UPDATE "
        "ON technicians FOR EACH ROW EXECUTE FUNCTION "
        "guard_accounting_timezone()"
    )
    op.execute(
        "CREATE TRIGGER expense_accounting_timezone BEFORE INSERT ON "
        "expense_revisions FOR EACH ROW EXECUTE FUNCTION "
        "guard_accounting_timezone()"
    )
    op.execute("""
CREATE FUNCTION guard_expense_session_owner() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF NEW.expense_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM technician_expenses
WHERE id=NEW.expense_id AND technician_id=NEW.technician_id)
        THEN RAISE EXCEPTION 'EXPENSE_SESSION_OWNER_MISMATCH' USING ERRCODE='23514'; END
IF;
        RETURN NEW;
      END $$""")
    op.execute(
        "CREATE TRIGGER expense_session_owner BEFORE INSERT OR UPDATE ON "
        "technician_form_sessions FOR EACH ROW EXECUTE FUNCTION "
        "guard_expense_session_owner()"
    )


def downgrade():
    op.execute("""DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM technician_expenses) OR EXISTS (SELECT 1 FROM
expense_revisions)
        OR EXISTS (SELECT 1 FROM technician_form_sessions WHERE purpose='EXPENSE')
        OR EXISTS (SELECT 1 FROM technicians WHERE accounting_timezone IS NOT NULL)
      THEN RAISE EXCEPTION 'EXPENSE_HISTORY_ROLLBACK_REFUSED'; END IF;
    END $$""")
    op.execute("DROP FUNCTION guard_expense_session_owner() CASCADE")
    op.execute("DROP FUNCTION guard_accounting_timezone() CASCADE")
    op.execute("DROP FUNCTION guard_expense_sequence() CASCADE")
    op.execute("DROP FUNCTION guard_expense_history() CASCADE")
    op.drop_constraint("fk_expense_current_revision", "technician_expenses", type_="foreignkey")
    op.drop_constraint(op.f("ck_technician_form_sessions_purpose"), "technician_form_sessions")
    op.create_check_constraint(
        op.f("ck_technician_form_sessions_purpose"),
        "technician_form_sessions",
        "purpose = 'WORK_REPORT'",
    )
    op.drop_constraint(op.f("ck_technician_form_sessions_submission"), "technician_form_sessions")
    op.create_check_constraint(
        op.f("ck_technician_form_sessions_submission"),
        "technician_form_sessions",
        (
            "(status = 'SUBMITTED' AND report_id IS NOT NULL AND submitted_at IS "
            "NOT NULL AND payload_hash IS NOT NULL) OR (status <> 'SUBMITTED' AND "
            "report_id IS NULL AND submitted_at IS NULL AND payload_hash IS NULL)"
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technicians", "accounting_timezone")
    op.drop_constraint(
        op.f("fk_technician_form_sessions_expense_id_technician_expenses"),
        "technician_form_sessions",
        type_="foreignkey",
    )
    op.drop_column("technician_form_sessions", "expense_id")
    op.drop_index(op.f("ix_expense_revisions_expense_date"), table_name="expense_revisions")
    op.drop_table("expense_revisions")
    op.drop_index(op.f("ix_technician_expenses_technician_id"), table_name="technician_expenses")
    op.drop_table("technician_expenses")
    # ### end Alembic commands ###
